# Generated by Django 6.0.4 on 2026-04-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('produtos', '0002_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='preco_unitario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preco_unitario', to='produtos.produto'),
        ),
    ]
